### ISSUE TITLE
[HashcatNode] Needs Windows Node

### ISSUE THREAD

**Issue by kallibr47** [hegusung/WebHashcat#21]
As i can understand, Node was written only to Linux, but i have my hashcat on Windows. If you can, please make Node avaliable to Windows too.

**Comment by hegusung** [comment]
I will do this very soon, I am facing the same issue right now. Thank you for your report

**Comment by hegusung** [comment]
Hashcatnode can now run on both Windows and Linux.

However it has a limitation, only 1 hashcat session can run at a time on Windows. This is due to the fact that the implementation of the user input in hashcat if very different between linux and windows.

See https://github.com/hashcat/hashcat/blob/9dffc69089d6c52e6f3f1a26440dbef140338191/src/terminal.c#L477 for technical details
